codecov:
  branch: main
  strict_yaml_branch: main
  require_ci_to_pass: yes
  bot: "codecov-io"
  ci:
    - "circleci.com"
  max_report_age: 48
  disable_default_path_fixes: no

coverage:
  precision: 2
  round: down
  range: "60...90"

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

ignore:
  - "docs"
  - "aroma/_version.py"
  - "**/__init__.py"
  - "**/**/__init__.py"
  - "aroma/tests"
  - ".*rc"
  - ".github"

comment:
  layout: "reach,diff,flags,tree"
  behavior: default
  require_changes: no
